steps:
# build container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.' ]

# push container image
- name: "gcr.io/cloud-builders/docker"
  args: [ "push", "gcr.io/$PROJECT_ID/gcpdevops" ]

# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --file=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=asia-southeast1-c
  - --cluster=gke-gcp-devops
  - --namespace=gcp-devops-gke
