# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
  namespace: gcp-devops-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: nginx-container
        image: gcr.io/ultimate-opus-466117-j5/gcpdevops-dev
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-gke-service
  namespace: gcp-devops-dev
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  type: LoadBalancer
  selector:
    app: gcp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
