apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
  namespace: gcp-devops-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: nginx-container
        image: gcr.io/ultimate-opus-466117-j5/gcpdevops:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
